version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: students-api
    environment:
      POSTGRES_USER: nucba
      POSTGRES_PASSWORD: nucba
      POSTGRES_DB: nucba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_students
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
